export async function testAllPS(PS, isLog = false) {
    if (isLog) console.log('t"settings.setControlsAsync"')
    await PS('settings.setControlsAsync')
    if (isLog) console.log('t"getLanguageAsync"')
    await PS('getLanguageAsync')
    if (isLog) console.log('t"downloadMusicItemAsync"')
    await PS('downloadMusicItemAsync')
    if (isLog) console.log('t"toThisSourceAsync"')
    await PS('toThisSourceAsync')
    if (isLog) console.log('t"showActionsDialogAsync"')
    await PS('showActionsDialogAsync')
    if (isLog) console.log('t"closeActionsDialogAsync"')
    await PS('closeActionsDialogAsync')
    if (isLog) console.log('t"updateAppStateAsync"')
    await PS('updateAppStateAsync')
    if (isLog) console.log('t"initPageStacksAsync"')
    await PS('initPageStacksAsync')
    if (isLog) console.log('t"currPageStackName_getAsync"')
    await PS('currPageStackName_getAsync')
    if (isLog) console.log('t"currPageStackName_setAsync"')
    await PS('currPageStackName_setAsync')
    if (isLog) console.log('t"currTabIdx_getAsync"')
    await PS('currTabIdx_getAsync')
    if (isLog) console.log('t"currTabIdx_setAsync"')
    await PS('currTabIdx_setAsync')
    if (isLog) console.log('t"tabs_getAsync"')
    await PS('tabs_getAsync')
    if (isLog) console.log('t"tabs_setAsync"')
    await PS('tabs_setAsync')
    if (isLog) console.log('t"currSearchTabIdx_getAsync"')
    await PS('currSearchTabIdx_getAsync')
    if (isLog) console.log('t"currSearchTabIdx_setAsync"')
    await PS('currSearchTabIdx_setAsync')
    if (isLog) console.log('t"searchTabs_getAsync"')
    await PS('searchTabs_getAsync')
    if (isLog) console.log('t"searchTabs_setAsync"')
    await PS('searchTabs_setAsync')
    if (isLog) console.log('t"navType_getAsync"')
    await PS('navType_getAsync')
    if (isLog) console.log('t"navType_setAsync"')
    await PS('navType_setAsync')
    if (isLog) console.log('t"isShowPreloader_getAsync"')
    await PS('isShowPreloader_getAsync')
    if (isLog) console.log('t"isShowPreloader_setAsync"')
    await PS('isShowPreloader_setAsync')
    if (isLog) console.log('t"isShowSearch_getAsync"')
    await PS('isShowSearch_getAsync')
    if (isLog) console.log('t"isShowSearch_setAsync"')
    await PS('isShowSearch_setAsync')
    if (isLog) console.log('t"rightControls_getAsync"')
    await PS('rightControls_getAsync')
    if (isLog) console.log('t"rightControls_setAsync"')
    await PS('rightControls_setAsync')
    if (isLog) console.log('t"updateThumbnailFromUrlAsync"')
    await PS('updateThumbnailFromUrlAsync')
    if (isLog) console.log('t"currPageStack.length_getAsync"')
    await PS('currPageStack.length_getAsync')
    if (isLog) console.log('t"currPageStack.last_getAsync"')
    await PS('currPageStack.last_getAsync')
    if (isLog) console.log('t"currPageStack.setLast"')
    await PS('currPageStack.setLast')
    if (isLog) console.log('t"currPageStack.push"')
    await PS('currPageStack.push')
    if (isLog) console.log('t"currPageStack.pop"')
    await PS('currPageStack.pop')
    if (isLog) console.log('t"currPageIdAsync"')
    await PS('currPageIdAsync')
    if (isLog) console.log('t"currPage.typeAsync"')
    await PS('currPage.typeAsync')
    if (isLog) console.log('t"currMusicPage.title_getAsync"')
    await PS('currMusicPage.title_getAsync')
    if (isLog) console.log('t"currMusicPage.title_setAsync"')
    await PS('currMusicPage.title_setAsync')
    if (isLog) console.log('t"currMusicPage.sectionlist_getAsync"')
    await PS('currMusicPage.sectionlist_getAsync')
    if (isLog) console.log('t"currMusicPage.sectionlist_setAsync"')
    await PS('currMusicPage.sectionlist_setAsync')
    if (isLog) console.log('t"currMusicPage.header_getAsync"')
    await PS('currMusicPage.header_getAsync')
    if (isLog) console.log('t"currMusicPage.header_setAsync"')
    await PS('currMusicPage.header_setAsync')
    if (isLog) console.log('t"currMusicPage.acitonBtn_getAsync"')
    await PS('currMusicPage.acitonBtn_getAsync')
    if (isLog) console.log('t"currMusicPage.acitonBtn_setAsync"')
    await PS('currMusicPage.acitonBtn_setAsync')
    if (isLog) console.log('t"currMusicPage.props_getAsync"')
    await PS('currMusicPage.props_getAsync')
    if (isLog) console.log('t"currMusicPage.props_setAsync"')
    await PS('currMusicPage.props_setAsync')
    if (isLog) console.log('t"playback.playByIdx"')
    await PS('playback.playByIdx')
    if (isLog) console.log('t"queue.insertAllAsync"')
    await PS('queue.insertAllAsync')
    if (isLog) console.log('t"queue.addAllAsync"')
    await PS('queue.addAllAsync')
    if (isLog) console.log('t"queue.removeRangeAsync"')
    await PS('queue.removeRangeAsync')
    if (isLog) console.log('t"queue.clearAsync"')
    await PS('queue.clearAsync')
    if (isLog) console.log('t"queue.getTrackAsync"')
    await PS('queue.getTrackAsync')
    if (isLog) console.log('t"queue.currTrackIdx_getAsync"')
    await PS('queue.currTrackIdx_getAsync')
    if (isLog) console.log('t"queue.currTrackIdx_setAsync"')
    await PS('queue.currTrackIdx_setAsync')
    if (isLog) console.log('t"queue.lengthAsync"')
    await PS('queue.lengthAsync')
    if (isLog) console.log('t"propertyStorage.get"')
    await PS('propertyStorage.get')
    if (isLog) console.log('t"propertyStorage.set"')
    await PS('propertyStorage.set')
    if (isLog) console.log('t"errorManager.get"')
    await PS('errorManager.get')
    if (isLog) console.log('t"errorManager.set"')
    await PS('errorManager.set')
}
