// Generated by ts-to-zod
import { z } from "zod";
import { NavType, BodyType, ListType, WrapperType, IconName, DownloaderType, ControlsType, ItemActionsContextType } from "./enums";

export const sKeyValue = z.record(z.string(), z.any());
export type KeyValue = z.infer<typeof sKeyValue>

export const sNavType = z.enum(NavType);

export const sBodyType = z.enum(BodyType);

export const sListType = z.enum(ListType);

export const sWrapperType = z.enum(WrapperType);

export const sIconName = z.enum(IconName);

export const sDownloaderType = z.enum(DownloaderType);

export const sControlsType = z.enum(ControlsType);

export const sItemActionsContextType = z.enum(ItemActionsContextType);

// export const sSendMessageType = z.function({ input: [z.string(), z.string()], output: z.any() });

export const sItemAction = z.object({
    text: z.string(),
    icon: sIconName.optional(),
    callback: z.function({ input: [], output: z.void() })
});
export type ItemAction = z.infer<typeof sItemAction>

export const sItem = z.object({
    id: z.string(),
    title: z.string(),
    subtitle: z.string(),
    thumbnailUrl: z.string()
});
export type Item = z.infer<typeof sItem>

export const sIndexedItem = z.object({
    index: z.number(),
    item: sItem
});
export type IndexedItem = z.infer<typeof sIndexedItem>

export const sMusicItem = sItem.extend({
    id: z.string(),
    title: z.string(),
    subtitle: z.string(),
    thumbnailUrl: z.string(),
    artist: z.object({
        id: z.string(),
        title: z.string()
    }),
    album: z.object({
        id: z.string(),
        title: z.string()
    }),
    duration: z.number(),
    downloaderType: sDownloaderType,
    extension: z.string()
});
export type MusicItem = z.infer<typeof sMusicItem>

export const sGroupItem = sItem.extend({
    id: z.string(),
    title: z.string(),
    subtitle: z.string(),
    thumbnailUrl: z.string(),
    props: sKeyValue.optional()
});
export type GroupItem = z.infer<typeof sGroupItem>

export const sActionBtnDescr = z.object({
    text: z.string(),
    icon: sIconName.optional(),
    callbackName: z.string(),
    callbackArgs: z.array(z.string())
});
export type ActionBtnDescr = z.infer<typeof sActionBtnDescr>

export const sPageHeaderDescr = z.object({
    title: z.string(),
    subtitle: z.string().optional(),
    thumbnailUrl: z.string().optional(),
    actionBtn: sActionBtnDescr.optional()
});
export type PageHeaderDescr = z.infer<typeof sPageHeaderDescr>

export const sDownloadProps = z.object({
    id: z.string(),
    onDataReceived: z.function({ input: [z.number(), z.number()], output: z.void() })
});
export type DownloadProps = z.infer<typeof sDownloadProps>

export const sSectionHeaderDescr = z.object({
    title: z.string().optional(),
    subtitle: z.string().optional(),
    actionBtn: sActionBtnDescr.optional()
});
export type SectionHeaderDescr = z.infer<typeof sSectionDescrJs>

export const sSectionDescrJs = z.object({
    header: sSectionHeaderDescr.optional(),
    listType: sListType,
    itemlist: z.array(sItem),
    isBigTile: z.boolean().optional(),
    rowsCount: z.number(),
    props: sKeyValue.optional()
});
export type SectionDescrJs = z.infer<typeof sSectionDescrJs>

export const sPageDescrJs = z.object({
    title: z.string().optional(),
    sectionlist: z.array(sSectionDescrJs),
    header: sPageHeaderDescr.optional(),
    actionBtn: sActionBtnDescr.optional(),
    props: sKeyValue.optional()
});
export type PageDescrJs = z.infer<typeof sPageDescrJs>
